default: &default
  test_cronjob:
    class: TestJob
    queue: background
    args: [ 1000, { batch_size: 500 } ]
    schedule: every minute

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
